//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMBPageBuilder.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DMBPageBuilderInternalLocalization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DMBPageBuilderInternalLocalization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("BootstrapBuilder.Resources.DMBPageBuilderInternalLocalization", typeof(DMBPageBuilderInternalLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string PageAlert_Exception_Title {
            get {
                return ResourceManager.GetString("PageAlert_Exception_Title", resourceCulture) ?? string.Empty;
            }
        }

        internal static string PageAlert_InvalidCaptcha_Message {
            get {
                return ResourceManager.GetString("PageAlert_InvalidCaptcha_Message", resourceCulture) ?? string.Empty;
            }
        }

        internal static string PageAlert_InvalidCaptcha_Title {
            get {
                return ResourceManager.GetString("PageAlert_InvalidCaptcha_Title", resourceCulture) ?? string.Empty;
            }
        }

        internal static string PageAlert_InvalidModel_Message {
            get {
                return ResourceManager.GetString("PageAlert_InvalidModel_Message", resourceCulture) ?? string.Empty;
            }
        }

        internal static string PageAlert_InvalidModel_Title {
            get {
                return ResourceManager.GetString("PageAlert_InvalidModel_Title", resourceCulture) ?? string.Empty;
            }
        }
    }
}
